project:
  type: website
  output-dir: _site

website:
  title: "Brayden Cherry"
  favicon: images/favicon.svg
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Case Studies
        menu:
          - href: projects/project-1.qmd
            text: ShadowRock Client Analytics Platform
          - href: projects/project-2.qmd
            text: Rags to Robes Community Resource Website
          - href: projects/project-3.qmd
            text: ASARCO Workforce Analytics
          - href: projects/project-4.qmd
            text: Storage Scholars Operations Management
          - href: projects/project-6.qmd
            text: Trade Insights Pro Journal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
